controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
  - name: fake_left_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper_l_joint
  - name: fake_right_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper_r_joint
initial:  # Define initial robot poses.
#  - group: left_arm
#    pose: home

  []